name: api
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ../volumes/mysql:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD}",
        ]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 30s

  web:
    build:
      context: .
      dockerfile: test.dockerfile
    ports:
      - "8000:8000"
    environment:
      - MYSQL_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      - REDIRECT_URI=${REDIRECT_URI}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - AWS_REGION=${AWS_REGION}
      - USER_POOL_ID=${USER_POOL_ID}
      - COGNITO_USER_CLIENT_ID=${COGNITO_USER_CLIENT_ID}
      - COGNITO_USER_CLIENT_SECRET=${COGNITO_USER_CLIENT_SECRET}
      - COGNITO_TOKEN_ENDPOINT=${COGNITO_TOKEN_ENDPOINT}
    volumes:
      - .:/api
    depends_on:
      db:
        condition: service_healthy
