name: api
services:
  db:
    image: mysql:8.0
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ../volumes/mysql:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: test.dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    environment:
      - MYSQL_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
    volumes:
      - .:/api
    depends_on:
      - db
