name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: "eu-north-1"
  USER_POOL_ID: "eu-north-1_yl0s2JiPS"
  COGNITO_USER_CLIENT_ID: "4ejoc1sludu6oio9tmgrvcjb3t"
  COGNITO_USER_CLIENT_SECRET: ${{ secrets.COGNITO_USER_CLIENT_SECRET }}
  COGNITO_TOKEN_ENDPOINT: "https://703671939478-gap-es.auth.eu-north-1.amazoncognito.com/oauth2/token"
  MYSQL_ROOT_PASSWORD: "123456"
  MYSQL_DATABASE: "users"
  MYSQL_USER: "admin"
  MYSQL_PASSWORD: "123456"

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full clone for SonarCloud analysis

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies with Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry tox
          poetry install

      - name: Run tests with tox
        run: tox -e py

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub Token for SonarCloud
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # SonarCloud token from GitHub Secrets
